repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-ast

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [torch, torchvision, numpy, types-PyYAML]

 # 🔒 Silent Killers — audit Python for bad exception handling
  - repo: https://github.com/kilojoules/silent-killers
    rev: v0.1.7
    hooks:
      - id: silent-killers-audit
        files: ^(src/|scripts/|tests/).*\.py$
