# Paths
data_dir: "../GTSRB_dataset/GTSRB/Final_Training/Images/"
test_data_dir: "../GTSRB_dataset/GTSRB_test/Final_Test/Images/"

# General experiment parameters
epochs: 30
learning_rate: 0.0005
batch_size: 64

# List of effects to use for training models
# Train only the baseline and one complex model to start.
training_conditions:
  - none
  - light_rain
  - light_dust

# List of effects to use for testing
# Test against a small, representative subset of conditions.
test_conditions:
  - none
  - light_rain
  - light_dust
  - heavy_rain
  - heavy_dust
  - mixed_light


model:
  architecture:
    - type: Conv2d
      params: {in_channels: 3, out_channels: 16, kernel_size: 5}
    - type: ReLU
    - type: MaxPool2d
      params: {kernel_size: 2, stride: 2}
    - type: Flatten
    - type: Linear
      params: {out_features: 84}
    - type: ReLU
    - type: Linear
      params: {out_features: 43}
