name: CI

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    env:
      MPLBACKEND: Agg
      CUDA_VISIBLE_DEVICES: ""
      PYTHONWARNINGS: "ignore::UserWarning"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - run: python -m pip install --upgrade pip wheel setuptools
      - run: pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
      - run: pip install pytest pytest-cov pre-commit
      - run: pip install -e .
      - run: pytest -q
